### ISSUE TITLE
max crystal connection distance should be a configurable value

### ISSUE THREAD

**Issue by HamaIndustries** [Lgmrszd/anshar#10]
![image](https://github.com/Lgmrszd/anshar/assets/11379516/4fe2dbeb-fe0c-47be-ab18-f5f0dff4d670)

**Comment by Lgmrszd** [comment]
Distance check for Linked Crystal added a while ago.
"Config" (via gamerule) added in 898e6890048afd64796636768f0ceddf68d60efa
