### ISSUE TITLE
Star Gate jump sound keeps playing second time after jumping

### ISSUE THREAD

**Issue by Lgmrszd** [Lgmrszd/anshar#17]

**Comment by Lgmrszd** [comment]
Oh and I checked the audio file, the very end of the arrival doesn't play and it just starts playing the audio from the beginning.

**Comment by Lgmrszd** [comment]
More details:
- Doesn't happen if you release forward button right after jumping. But most of the time, you keep pressing it, and while you do, sound starts playing again and doesn't get cancelled when you stop pressing the button.

**Comment by HamaIndustries** [comment]
closed by 490176abe1ec6a20adca829ba69f344087ccfaad

**Comment by HamaIndustries** [comment]
closed by 490176abe1ec6a20adca829ba69f344087ccfaad
