### ISSUE TITLE
display name of present beacon node when entering network (or while embedded in general?)

### ISSUE THREAD

**Issue by HamaIndustries** [Lgmrszd/anshar#18]

**Comment by HamaIndustries** [comment]
![image](https://github.com/Lgmrszd/anshar/assets/11379516/4c5a74fb-1cb1-4309-8a28-c1f83ecc2b20)

**Comment by Lgmrszd** [comment]
![image](https://github.com/Lgmrszd/anshar/assets/16291541/dddf5b1b-5aeb-446e-8a1e-b5f39ef1d98f)
It shows the name of the node you're looking at (something already showing anyway) not the current location

**Comment by HamaIndustries** [comment]
closed by 0e177be
