### ISSUE TITLE
Getting into the beam and then jumping while constantly holding W skips jump sound

### ISSUE THREAD

**Issue by Lgmrszd** [Lgmrszd/anshar#31]

**Comment by HamaIndustries** [comment]
really getting into the weeds here aren't we

**Comment by HamaIndustries** [comment]
turns out we were setting the jump target prematurely. PlayerTransportClient logic assumes that when `nearest` is not null, we are jumping. The variable should be either renamed to something better like `jumpTarget`, or some clearer means of declaring jump state should be set up.
