### ISSUE TITLE
Why anshar 0.0.15 is not pushed?

### ISSUE THREAD

**Issue by ditt0132** [Lgmrszd/anshar#41]
it is in modrinth, but not here!
i used playsound and found some extra music, so im searching for when it is used
and i cant, so i decompiled jar and i got 3 more music! why?

please upload 0.0.15!

**Comment by ditt0132** [comment]
and, some music name and its id does not match!

**Comment by Lgmrszd** [comment]
It is pushed, just on the dev branch: https://github.com/Anshar-Eternalis/anshar/blob/dev/gradle.properties

@HamaIndustries can you look into music ids

**Comment by ditt0132** [comment]
Okay thanks ill check it out
sorry for fool issue
maybe i need to close this?
or, ill just leave this for music id and name matching?

**Comment by HamaIndustries** [comment]
Leave it up, thanks for letting us know.

**Comment by HamaIndustries** [comment]
I'm going to keep the names because it's a secret sound event. Spoilers, but the music plays when you spend a few minutes inside Anshar. I'll merge dev into main now, good catch.
