### ISSUE TITLE
destroying a beacon with end crystal attached leaves crystal connected to air

### ISSUE THREAD

**Issue by HamaIndustries** [Lgmrszd/anshar#6]

**Comment by Lgmrszd** [comment]
We need to decide how it needs to be handles -- do we need a crystal to be disconnected permanently or do we want it to remember beacon pos and reconnect visually once it's there again?

**Comment by Lgmrszd** [comment]
Decided to keep the visible connection with a beacon even if it's not active

**Comment by Lgmrszd** [comment]
Fixed in ecb8088181d72fc87c065b9cfc181f5433deb9c9
